### ISSUE TITLE
doubts on the paper and dataset

### ISSUE THREAD

**Issue by yhlleo** [KangchengLiu/Crack-Detection-and-Segmentation-Dataset-for-UAV-Inspection#1]
Hi @KangchengLiu , it seems that both the method and dataset used in this project is highly built on our previous project: https://github.com/yhlleo/DeepCrack. However, these were not mentioned in your main paper at all. It's not fair for us. Please highlight our original contributions in your project!

**Comment by KangchengLiu** [comment]
Hi, we have added your work as citations. It should be noted that we have designed methods both for crack detection and crack segmentation, and our datasets are much more abundant than yours.
