### ISSUE TITLE
Semantic Segmentation

### ISSUE THREAD

**Issue by ChrisBuobSBB** [KangchengLiu/Crack-Detection-and-Segmentation-Dataset-for-UAV-Inspection#3]
Hello @KangchengLiu , 

Very nice project and thanks for the crack detection notebook. Do you by any chance also have a nb with the code for the semantic segmentation? If yes, it would be super helpful if you could push it to this repo as well. Thanks a lot!

**Comment by KangchengLiu** [comment]
Pushed. Pls give a star to this and other repo if you find them useful.

**Comment by ChrisBuobSBB** [comment]
Wow. Thanks a lot for the insanely quick reply! I would give you 100 stars if possible :)

**Comment by KangchengLiu** [comment]
Yes, feel free to star and refer to my other projects such as [Feature-Geometric-Net-FG-Net](https://github.com/KangchengLiu/Feature-Geometric-Net-FG-Net) and the newly released [RM3D](https://github.com/KangchengLiu/RM3D) !!

**Comment by KangchengLiu** [comment]
1.10 is ok
