### ISSUE TITLE
Correspondence model

### ISSUE THREAD

**Issue by YunfanLing** [KangchengLiu/Crack-Detection-and-Segmentation-Dataset-for-UAV-Inspection#5]
Hi! Thanks for sharing your code. I just read your paper and couldn't figure what is the correspondence model in your code
![image](https://user-images.githubusercontent.com/102476857/232333928-a1b11367-f431-4e29-8b89-5c20ef4d71ab.png)
Is the custom_model here the Seg-former model mentions in your paper? What about the other models here in your code correspond to the model in your code? Thanks.
![image](https://user-images.githubusercontent.com/102476857/232334124-b1f18e60-d1ab-404a-89ba-c32d8fa2acbb.png)

**Comment by KangchengLiu** [comment]
The implementations are now deployed into projects and will be updated when available.
