### ISSUE TITLE
Is DeepLabV3_plus with Crack-DA framework?

### ISSUE THREAD

**Issue by YunfanLing** [KangchengLiu/Crack-Detection-and-Segmentation-Dataset-for-UAV-Inspection#6]
Hi Kangcheng! I am trying to use your model to train a crack dataset from Kaggle. Is that [DeepLabV3.py](https://github.com/KangchengLiu/Crack-Detection-and-Segmentation-Dataset-for-UAV-Inspection/blob/master/Segmentation/models/DeepLabV3.py) here the DeepLabV3 model with the Crack-DA framework? Thanks a lot.

**Comment by KangchengLiu** [comment]
Yes, the da is simple but effective with depth and edge info.

**Comment by YunfanLing** [comment]
Thanks! 

Do you remember what is the version of TensorFlow you are using on this project? I got a lot of errors.
